name: Linting Koan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pyflakes:
    name: pyflakes formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get install -y python3-pyflakes
      - name: Run pyflakes
        run: pyflakes3 *.py bin/koan bin/cobbler-register koan/*.py
  black:
    name: black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --safe --verbose"
          version: "22.3.0"
